### ISSUE TITLE
Inventory Plugin

### ISSUE THREAD

**Issue by dtrieu80** [stolostron/ocmplus.cm#29]
**As an** Ansible automation engineer
**I would like to** be able to utilize an inventory plugin that lists the managed clusters under a hub as well as identify the nodes that each cluster is comprised of.
**So that** I can manage clusters adhoc as well as make changes to underlying machines via Ansible automation.

Example 
```
{
  "hub_cluster": {
    "hosts": ["cluster001"],
    "vars": {
      "var1": true
    },
    "children": ["group002"]
  },
  "managed_clusters": {
    "hosts": ["cluster002", "cluster003", "cluster004"],
    "vars": {
      "var2": 500
    },
    "children": []
  },
  "labelA": {
    "hosts": ["cluster001", "cluster002"],
    "vars": {}
  },
  "labelB": {
    "hosts": ["cluster003", "cluster004"],
    "vars": {}
  },
  "cluster001_wrks": {
    "hosts": ["host4", "host5", "host6"]
  },
  "cluster001_ctls": {
    "hosts": ["host1", "host2", "host3"]
  },
  "all": {
    "children": ["ungrouped"]
  },
  "ungrouped": {
    "children": []
  },
  "_meta": {
    "hostvars": {
      "cluster001": {
        "var001": "value"
      },
      "cluster002": {
        "var002": "value"
      },
      "host1": {
        "fqdn": "host1.acme.com",
        "ipAddress": "1.2.3.4"
      }
    }
  }

}
```

**Comment by hanqiuzh** [comment]
Based on last community call, we will not store any login information in the inventory, and for the first stage, we will not store node information either. 

Thus, currently we will only store cluster-name in groups, and I'm currently having an experiment draft PR https://github.com/open-cluster-management/ocmplus.cm/pull/35

Basically we will need token & apiserver url information to manage a cluster, and I created another 2 addons to pull those information, which are also in the draft PR. Let's discuss more about use cases in the next community call.

**Comment by nathanweatherly** [comment]
Implementation merged. Discussing/demoing at workgroup meeting today! Future discussion to follow here!
