### ISSUE TITLE
Sanity test import is throwing error "import of "ansible.errors" is not allowed in this context"

### ISSUE THREAD

**Issue by taragu** [stolostron/ocmplus.cm#32]
Sanity test import is throwing error `import of "ansible.errors" is not allowed in this context` for `plugins/modules/import_eks.py` and `plugins/module_utils/import_utils.py`.
Need to figure out why and solve this problem and remove the corresponding lines in the ignore file.

**Comment by nathanweatherly** [comment]
Need to stop ignoring errors thrown by sanity tests and actually fix the issues. Don't think we're using ansible errors properly. Han to double-check.

**Comment by hanqiuzh** [comment]
ansible.errors are removed in https://github.com/stolostron/ocmplus.cm/pull/59
closing
