### ISSUE TITLE
Incorporate inventory plugin w/ Ansible Tower functionality

### ISSUE THREAD

**Issue by nathanweatherly** [stolostron/ocmplus.cm#41]
With Vault, we can securely store tokens retrieved by the inventory plugin

**Comment by nathanweatherly** [comment]
@hanqiuzh has this done, @hanqiuzh to link AAP doc in this issue before closing

**Comment by hanqiuzh** [comment]
doc https://docs.google.com/document/d/1aSQRsUmeZmvcFiFUq-fqXtp7giCUu2yv8X-d4W-VqVQ/edit#heading=h.k2tykppgjvnd
