### ISSUE TITLE
Policy Plugin

### ISSUE THREAD

**Issue by nathanweatherly** [stolostron/ocmplus.cm#48]
Goal: Provide a kube-native experience for users wanting to leverage ACM's policy functionality

- Provide a path to a file containing a valid YAML definition of an object or objects to be created, updated, deleted or validated existence.
- Convert the definition of an object or objects into a GRC policy
- Convert cluster selections into a Placement rule 
- Deploy the policy to the selected managed clusters

**Comment by nathanweatherly** [comment]
Hao currently working on feature spec

**Comment by nathanweatherly** [comment]
Tsu Phin has been working on a prototype and design for this. @tphee Can you please record your updates here?

**Comment by tphee** [comment]
`Feature Spec`: https://docs.google.com/document/d/1s_cLVvma31nlTpsy1FpZDfObIuDzzrUPFGZr_Bub2Y4/edit#heading=h.eyy18vjt0pj4

`Module`: https://github.com/stolostron/incubator/blob/main/plugins/modules/policyset.py
