### ISSUE TITLE
Modify plugin module to specify TTL configuration

### ISSUE THREAD

**Issue by nathanweatherly** [stolostron/ocmplus.cm#77]
TTL support now in MSA as alpha feature. Review Ansible precedents for how best to surface this configuration in our plugin spec.

**Comment by nathanweatherly** [comment]
@hanqiuzh can you please update?

**Comment by hanqiuzh** [comment]
PR merged: https://github.com/stolostron/ocmplus.cm/pull/80
also we have done a demo on playback. closing
