### ISSUE TITLE
Add testing framework for plugin beyond sanity testing

### ISSUE THREAD

**Issue by nathanweatherly** [stolostron/ocmplus.cm#79]
Review Ansible precedents when deciding how these tests should be structured and what they should test

**Comment by nathanweatherly** [comment]
Notes from planning:

```
Unit tests, functional tests, integration tests. Also integrate into CI.
```

**Comment by hanqiuzh** [comment]
`ansible-test integration` has logic to handle special settings for multiple special collections; for example kubernetes.core, which runs a container of OCP 3.9 inside ansible-test. 
We will not do that. There is config file integration_config.yml file to give variables. 
Plan was to in GH action gen yaml file to fill in values and use that.

**Comment by nathanweatherly** [comment]
been done!
