### ISSUE TITLE
Update featureEnable plugin to reflect API changes in MultiClusterHub and MultiClusterEngine API

### ISSUE THREAD

**Issue by nathanweatherly** [stolostron/ocmplus.cm#81]
Currently the generic addon plugin only installs the addon if the addon is already enabled on the hub. We want to add an option to enable (/disable?) features on the hub from the generic addon plugin.

**Comment by hanqiuzh** [comment]
First PR: https://github.com/stolostron/ocmplus.cm/pull/89

**Comment by nathanweatherly** [comment]
@hanqiuzh can you please update with recent improvements?

**Comment by nathanweatherly** [comment]
Currently refactoring to reflect new MCE and MCH API changes.

**Comment by nathanweatherly** [comment]
Complexities:
- Waiting on completion of API rewrite from ACM's Install team (timeline independent from ours)

**Comment by hanqiuzh** [comment]
changes merged. closing
