### ISSUE TITLE
RBAC Plugin: Standardize paths to RBAC file(s)

### ISSUE THREAD

**Issue by nathanweatherly** [stolostron/ocmplus.cm#88]
Slack discussion: https://coreos.slack.com/archives/C02K4843LMQ/p1645554981081749

If paths to roles aren't a simple flat structure, things don't work (paraphrasing from Hao's findings)

**Comment by tphee** [comment]
I think if we change this:
https://github.com/stolostron/ocmplus.cm/blob/main/plugins/modules/managed_serviceaccount_rbac.py#L282

`rbac_template=dict(type='str', required=True),`

to:

`rbac_template=dict(type='path', required=True),`

might fix this issue?

**Comment by nathanweatherly** [comment]
Complexities:
- Proposed change is good change to make, but doesn't fix the issue
- Best solution is to document that the path to the RBAC files is a relative to playbook

(update do)
