### ISSUE TITLE
Generate RST Docs

### ISSUE THREAD

**Issue by nathanweatherly** [stolostron/ocmplus.cm#99]
RST docs should be the basis of our README(s) for the collection. 

Include re-generation of the RST docs in our CI as a github action

**Comment by nathanweatherly** [comment]
Discussed at scrum: 

For doc generation as part of a github action -> With every PR, generate docs to see if there is a difference in the resulting readme. If yes, commit change. Else, don't commit anything. 

tl;dr: attempt to update doc with each PR

**Comment by hanqiuzh** [comment]
Did some investigation on possibility of pushing a commit for the PR, but found difficulties of giving write permissions. As our PRs are from forked repo, and it will be a security issue if it has any write permission. This is actually good.

Currently we are having a github action which supports manual/scheduled doc update (shcedule still needs some tests)

**Comment by hanqiuzh** [comment]
closing as PR of rst docs got merged, and I will open new issue if the scheduling doesn't work as expected
